# Cancer Mortality Rate

# 1) Problem Description

In this case we will try to predict cancer mortality rates in US counties. In addition to that, we will try to answer some other questions by EDA, such as:

- What features causes the mortality rate to be higher / lower?

- Are some counties totally different than others?

- Which race, are most dangered by cancer?

And many many more.


All the data with column explanation is available here: https://data.world/nrippner/ols-regression-challenge.

# 2) Basic Imports and preparation for Data Exploration

General Imports for Data Clearing, And Data Exploratory

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats
import re

Setting up the display of Data Frames and plots.

In [21]:
pd.set_option("display.width",320)
pd.set_option("display.max_columns",40)
sns.set_style("whitegrid")

Reading the DataFrame

In [22]:
raw_data = pd.read_csv("cancer_reg.csv", encoding="windows-1250")

raw_data.head()

,avgAnnCount,avgDeathsPerYear,TARGET_deathRate,incidenceRate,medIncome,popEst2015,povertyPercent,studyPerCap,binnedInc,MedianAge,MedianAgeMale,MedianAgeFemale,Geography,AvgHouseholdSize,PercentMarried,PctNoHS18_24,PctHS18_24,PctSomeCol18_24,PctBachDeg18_24,PctHS25_Over,PctBachDeg25_Over,PctEmployed16_Over,PctUnemployed16_Over,PctPrivateCoverage,PctPrivateCoverageAlone,PctEmpPrivCoverage,PctPublicCoverage,PctPublicCoverageAlone,PctWhite,PctBlack,PctAsian,PctOtherRace,PctMarriedHouseholds,BirthRate
0,1397.0,469,164.9,489.8,61898,260131,11.2,499.748204,"(61494.5, 125635]",39.3,36.9,41.7,"Kitsap County, Washington",2.54,52.5,11.5,39.5,42.1,6.9,23.2,19.6,51.9,8.0,75.1,NaN,41.6,32.9,14.0,81.780529,2.594728,4.821857,1.843479,52.856076,6.118831
1,173.0,70,161.3,411.6,48127,43269,18.6,23.111234,"(48021.6, 51046.4]",33.0,32.2,33.7,"Kittitas County, Washington",2.34,44.5,6.1,22.4,64.0,7.5,26.0,22.7,55.9,7.8,70.2,53.8,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
2,102.0,50,174.7,349.7,49348,21026,14.6,47.560164,"(48021.6, 51046.4]",45.0,44.0,45.8,"Klickitat County, Washington",2.62,54.2,24.0,36.6,NaN,9.5,29.0,16.0,45.9,7.0,63.7,43.5,34.9,42.1,21.1,90.922190,0.739673,0.465898,2.747358,54.444868,3.729488
3,427.0,202,194.8,430.4,44243,75882,17.1,342.637253,"(42724.4, 45201]",42.8,42.2,43.4,"Lewis County, Washington",2.52,52.7,20.2,41.2,36.1,2.5,31.6,9.3,48.3,12.1,58.4,40.3,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
4,57.0,26,144.4,350.1,49955,10321,12.5,0.000000,"(48021.6, 51046.4]",48.3,47.8,48.9,"Lincoln County, Washington",2.34,57.8,14.9,43.0,40.0,2.0,33.4,15.0,48.2,4.8,61.6,43.9,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657

# 3) Data Cleaning and General Information about Dataset.

In [23]:
print(f"In dataset we have:\n{raw_data.shape[0]} rows,\n{raw_data.shape[1]} features.")

In dataset we have:
3047 rows,
34 features.

3.1 Checking the Datatypes of Dataset.

In [24]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3047 entries, 0 to 3046
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avgAnnCount              3047 non-null   float64
 1   avgDeathsPerYear         3047 non-null   int64
 2   TARGET_deathRate         3047 non-null   float64
 3   incidenceRate            3047 non-null   float64
 4   medIncome                3047 non-null   int64
 5   popEst2015               3047 non-null   int64
 6   povertyPercent           3047 non-null   float64
 7   studyPerCap              3047 non-null   float64
 8   binnedInc                3047 non-null   object
 9   MedianAge                3047 non-null   float64
 10  MedianAgeMale            3047 non-null   float64
 11  MedianAgeFemale          3047 non-null   float64
 12  Geography                3047 non-null   object
 13  AvgHouseholdSize         3047 non-null   float64
 14  PercentMarried           3047 non-null   float64
 15  PctNoHS18_24             3047 non-null   float64
 16  PctHS18_24               3047 non-null   float64
 17  PctSomeCol18_24          762 non-null    float64
 18  PctBachDeg18_24          3047 non-null   float64
 19  PctHS25_Over             3047 non-null   float64
 20  PctBachDeg25_Over        3047 non-null   float64
 21  PctEmployed16_Over       2895 non-null   float64
 22  PctUnemployed16_Over     3047 non-null   float64
 23  PctPrivateCoverage       3047 non-null   float64
 24  PctPrivateCoverageAlone  2438 non-null   float64
 25  PctEmpPrivCoverage       3047 non-null   float64
 26  PctPublicCoverage        3047 non-null   float64
 27  PctPublicCoverageAlone   3047 non-null   float64
 28  PctWhite                 3047 non-null   float64
 29  PctBlack                 3047 non-null   float64
 30  PctAsian                 3047 non-null   float64
 31  PctOtherRace             3047 non-null   float64
 32  PctMarriedHouseholds     3047 non-null   float64
 33  BirthRate                3047 non-null   float64
dtypes: float64(29), int64(3), object(2)
memory usage: 809.5+ KB

In [25]:
print(raw_data['binnedInc'].head()) # For this column, we will only grab the median value. We're not intreset in decyl value. We will do this using regular expression.


REGEX_PATTERN = "(?<=\(|\[)\d*\.{0,1}\d{0,900}"


raw_data['medianInc']=[re.search(REGEX_PATTERN, raw_data['binnedInc'][i]).group() for i in range(len(raw_data))]

raw_data['medianInc'] = raw_data['medianInc'].astype(float)

raw_data = raw_data.drop("binnedInc",axis=1)

0     (61494.5, 125635]
1    (48021.6, 51046.4]
2    (48021.6, 51046.4]
3      (42724.4, 45201]
4    (48021.6, 51046.4]
Name: binnedInc, dtype: object

<>:4: SyntaxWarning: invalid escape sequence '\('
<>:4: SyntaxWarning: invalid escape sequence '\('
/var/folders/n6/www0gbg912s1hbz7rz_kh0vc0000gn/T/ipykernel_1286/3531550370.py:4: SyntaxWarning: invalid escape sequence '\('
  REGEX_PATTERN = "(?<=\(|\[)\d*\.{0,1}\d{0,900}"

3.2 Checking Null Values in Dataset

In [26]:


[f"{col} - {np.round(raw_data[col].isnull().sum() / raw_data.shape[0],2)}% empty values" for col in raw_data.columns[raw_data.isnull().any()]]

['PctSomeCol18_24 - 0.75% empty values',
 'PctEmployed16_Over - 0.05% empty values',
 'PctPrivateCoverageAlone - 0.2% empty values']

<b>PctSomeCol18_24</b> - Percent of county residents ages 18-24 highest education attained: some college. In terms of this column, there's too much missing empty values. Filling them with median / mean can disturb information gathered from this feature.

In terms of other columns, we will fill them with nanmedian values.

In [27]:
PCT_EMPLOYED_NANMEDIAN = np.nanmedian(raw_data["PctEmployed16_Over"])
PCT_PRIVATE_NANMEDIAN = np.nanmedian(raw_data["PctPrivateCoverageAlone"])

print(f"Employed Nanmedian: {np.round(PCT_EMPLOYED_NANMEDIAN,3)}\nPrivate Coverage Nanmedian: {PCT_PRIVATE_NANMEDIAN}")

raw_data = raw_data.drop("PctSomeCol18_24",axis=1)
raw_data["PctEmployed16_Over"] = raw_data['PctEmployed16_Over'].fillna(PCT_EMPLOYED_NANMEDIAN)
raw_data["PctPrivateCoverageAlone"]=raw_data["PctPrivateCoverageAlone"].fillna(PCT_PRIVATE_NANMEDIAN)


print(f"Number of Empty Values in dataset: {raw_data.isnull().sum().sum()}")

clean_data = raw_data.copy()

Employed Nanmedian: 54.5
Private Coverage Nanmedian: 48.7
Number of Empty Values in dataset: 0

# 4. Exploratory Data Analysis

We will begin exploratory Data Analysis by checking the descriptive sastistics of the whole dataframe.

In [41]:
stats = clean_data.describe()
stats.loc['V'] = stats.loc['std'] / stats.loc['mean']
stats

,avgAnnCount,avgDeathsPerYear,TARGET_deathRate,incidenceRate,medIncome,popEst2015,povertyPercent,studyPerCap,MedianAge,MedianAgeMale,MedianAgeFemale,AvgHouseholdSize,PercentMarried,PctNoHS18_24,PctHS18_24,PctBachDeg18_24,PctHS25_Over,PctBachDeg25_Over,PctEmployed16_Over,PctUnemployed16_Over,PctPrivateCoverage,PctPrivateCoverageAlone,PctEmpPrivCoverage,PctPublicCoverage,PctPublicCoverageAlone,PctWhite,PctBlack,PctAsian,PctOtherRace,PctMarriedHouseholds,BirthRate,medianInc
count,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3.047000e+03,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000
mean,606.338544,185.965868,178.664063,448.268586,47063.281917,1.026374e+05,16.878175,155.399415,45.272333,39.570725,42.145323,2.479662,51.773679,18.224450,35.002068,6.158287,34.804660,13.282015,54.169970,7.852412,64.354939,48.502987,41.196324,36.252642,19.240072,83.645286,9.107978,1.253965,1.983523,51.243872,5.640306,43752.766328
std,1416.356223,504.134286,27.751511,54.560733,12040.090836,3.290592e+05,6.409087,529.628366,45.304480,5.226017,5.292849,0.429174,6.896928,8.093064,9.069722,4.529059,7.034924,5.394756,8.105295,3.452371,10.647057,9.019423,9.447687,7.841741,6.113041,16.380025,14.534538,2.610276,3.517710,6.572814,1.985816,10458.892963
min,6.000000,3.000000,59.700000,201.300000,22640.000000,8.270000e+02,3.200000,0.000000,22.300000,22.400000,22.300000,0.022100,23.100000,0.000000,0.000000,0.000000,7.500000,2.500000,17.600000,0.400000,22.300000,15.700000,13.500000,11.200000,2.600000,10.199155,0.000000,0.000000,0.000000,22.992490,0.000000,22640.000000
25%,76.000000,28.000000,161.200000,420.300000,38882.500000,1.168400e+04,12.150000,0.000000,37.700000,36.350000,39.100000,2.370000,47.750000,12.800000,29.200000,3.100000,30.400000,9.400000,48.900000,5.500000,57.200000,43.100000,34.500000,30.900000,14.850000,77.296180,0.620675,0.254199,0.295172,47.763063,4.521419,37413.800000
50%,171.000000,61.000000,178.100000,453.549422,45207.000000,2.664300e+04,15.900000,0.000000,41.000000,39.600000,42.400000,2.500000,52.400000,17.100000,34.700000,5.400000,35.300000,12.300000,54.500000,7.600000,65.100000,48.700000,41.100000,36.300000,18.800000,90.059774,2.247576,0.549812,0.826185,51.669941,5.381478,45201.000000
75%,518.000000,149.000000,195.200000,480.850000,52492.000000,6.867100e+04,20.400000,83.650776,44.000000,42.500000,45.300000,2.630000,56.400000,22.700000,40.700000,8.200000,39.650000,16.100000,60.000000,9.700000,72.100000,53.800000,47.700000,41.550000,23.100000,95.451693,10.509732,1.221037,2.177960,55.395132,6.493677,51046.400000
max,38150.000000,14010.000000,362.800000,1206.900000,125635.000000,1.017029e+07,47.400000,9762.308998,624.000000,64.700000,65.700000,3.970000,72.500000,64.100000,72.500000,51.800000,54.800000,42.200000,80.100000,29.400000,92.300000,78.900000,70.700000,65.100000,46.600000,100.000000,85.947799,42.619425,41.930251,78.075397,21.326165,61494.500000
V,2.335917,2.710897,0.155328,0.121714,0.255828,3.206037e+00,0.379726,3.408175,1.000710,0.132068,0.125586,0.173078,0.133213,0.444077,0.259120,0.735441,0.202126,0.406170,0.149627,0.439657,0.165443,0.185956,0.229333,0.216308,0.317724,0.195827,1.595803,2.081618,1.773466,0.128265,0.352076,0.239045

Based on descriptive statistics we can say, that we have a mix of scales in our dataset, some of them are measured in thousands, and some of them have really low values - this means, that in the future we will have to rescale our data. We can also say, that some of our features vary from the mean value, for example <b>studyPerCap</b> which can make our prediction a little bit more uncertain. We will deal with those features later.

Next, we will try to measure skewness.

In [107]:
[f"{column} : {np.round(scipy.stats.skew(clean_data[column]),3)}" for column in clean_data.columns 
    if clean_data[column].dtype != "O" and abs(np.round(scipy.stats.skew(clean_data[column]),3)) > 0.5]

['avgAnnCount : 10.675',
 'avgDeathsPerYear : 11.943',
 'incidenceRate : 0.772',
 'medIncome : 1.407',
 'popEst2015 : 14.283',
 'povertyPercent : 0.93',
 'studyPerCap : 8.709',
 'MedianAge : 9.985',
 'AvgHouseholdSize : -3.379',
 'PercentMarried : -0.653',
 'PctNoHS18_24 : 0.973',
 'PctBachDeg18_24 : 1.955',
 'PctBachDeg25_Over : 1.094',
 'PctUnemployed16_Over : 0.891',
 'PctWhite : -1.68',
 'PctBlack : 2.257',
 'PctAsian : 7.414',
 'PctOtherRace : 4.95',
 'PctMarriedHouseholds : -0.522',
 'BirthRate : 1.323']